language: python
python: 2.7

services:
  - docker
  - mysql
  - postgresql

env:
  matrix:
    - TOXENV=py27
    - TOXENV=flake8

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
      services:
        - docker
        - mysql
        - postgresql

install:
  - pip install -U tox wheel codecov
  - pip install -r requirements/tests.txt

before_install:
  - sudo apt-get update
  - sudo apt-get -y --force-yes -o Dpkg::Options::="--force-confold" install docker-engine mysql-server
  - git clone https://github.com/dajobe/hbase-docker
  - docker pull dajobe/hbase
  - mkdir data
  - ./hbase-docker/start-hbase.sh

before_script:
  - mysql -u root -e "set global innodb_large_prefix=1;"
  - mysql -u root -e "set global innodb_file_format='Barracuda';"
  - mysql -u root -e "set global innodb_file_per_table=true;"
  - tests/run_zmq_broker.sh

script: tox

after_success:
  - codecov

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapinghub
  password:
    secure: bG1ycgBJrVfgBsHAwaWScL2V1x52/aZy2znE2kFzFfYq95HS51mu1GO2PKwpATJyMCs/xUIKGhiBtoo8LzNmNU2kPgarQFwzpLkx2ninOm+3uAwuIfGGWsonBW/h854n+cNwppJOlfEOxvMVerVVpdV4EFeJfEkVYascwOBbnqo=
  on:
    branch: master
    tags: true
    condition: $TOXENV == py27
